source 'https://rubygems.org'

# Cocoapods
gem "motion-cocoapods", '1.3.0.rc1'
gem "cocoapods"

# RubyMotion
gem 'bubble-wrap', :require => ['bubble-wrap/core', 'bubble-wrap/rss_parser', 'bubble-wrap/http']
gem 'ProMotion', '~> 1.0'

# Rubygems
gem "rake", '>= 0.9.4'

# Development
gem 'awesome_print_motion'
