# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'bundler'

Bundler.setup
Bundler.require

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'RedditRss'
  app.frameworks += %w(CoreImage QuartzCore)

  app.pods do
    pod 'SDWebImage'
    pod 'NUI'
  end

end
