# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bundler'

Bundler.setup
Bundler.require

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Wrappers'
  # app.identifier = 'com.skookum.ConvergeSE'
  app.frameworks += ['QuartzCore']

  app.pods do
    pod 'SVProgressHUD'
  end

end
